spring.application.name=checkout-gateway
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server.port=${PORT:10000}
server.address=0.0.0.0